Dream/urls.py
from django.contrib import admin
from django.urls import path, include
from DreamApp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('services/', views.services, name='services'),
    path('team/', views.team, name='team'),
    path('about/', views.about, name='about'),
    path('galery/', views.galery, name='galery'),
    path('blog-list/<int:index>', views.blogs, name='blog'),
    path('blog-list/detalle/<int:pk>', views.blog_detail, name="blog-detail"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DreamApp/models.py
from django.contrib.auth.models import User
from django.db import models
from ckeditor.fields import RichTextField
from django.shortcuts import reverse
# Create your models here.

class General(models.Model):
    created_at = models.DateTimeField(verbose_name="Creado", auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Modificado")
    name = models.CharField(max_length=255,help_text="Nombre del negocio", verbose_name="Nombre")
    slogan_1 = models.CharField(max_length=255, verbose_name="Texto del Banner Inicio 1", help_text="Primer texto en la imagen del banner en la Página de inicio", blank=True, null=True)
    slogan_2 = models.CharField(max_length=255, verbose_name="Texto del Banner Inicio 2",help_text="Segundo texto en la imagen del banner de inicio", blank=True, null=True)
    slogan_3 = models.CharField(max_length=255, verbose_name="Texto del Banner Inicio 3",help_text="Tercer Texto en la imagen del banner de inicio", blank=True, null=True)
    text_1_solicitud = models.CharField(max_length=255, verbose_name="Primer texto de formulario solicitud",help_text="1er texto del Cartel arriba del formulario", blank=True, null=True)
    text_2_solicitud = models.CharField(max_length=255, verbose_name="Segundo texto de formulario solicitud",help_text="2do texto del Cartel arriba del formulario", blank=True, null=True)
    text_3_solicitud = models.CharField(max_length=255, verbose_name="Tercer texto de formulario solicitud",help_text="3er texto del Cartel arriba del formulario", blank=True, null=True)
    text_portafolio_inicio = models.CharField(max_length=255, verbose_name="Texto que encabeza el portafolio",help_text="Texto que encabeza el portafolio en inicio", blank=True, null=True)
    image_banner_1 = models.ImageField(upload_to='general', verbose_name="Imagen Banner Inicio",help_text="Imagen del Banner en la Página de inicio")
    text_1_about = models.CharField(max_length=255, verbose_name="Titulo de Contactos",
                                      help_text="Titulo de la página Nosotros", blank=True,
                                      null=True)
    descripcion_about = RichTextField(verbose_name="Descripcion de Nosotros",help_text="Descripción de la Página Nosotros")
    policity_privacity = RichTextField(verbose_name="Politica y Privacidad",help_text="Descripción de la Politica y la Privacidad")
    term_use = RichTextField(verbose_name="Terminos y Uso",help_text="Descripción de los terminos y Uso")
    image_about = models.ImageField(upload_to='general', verbose_name="Imagen de nosotros",help_text="Imagen de la página Nosotros")
    image_banner_2 = models.ImageField(upload_to='general', verbose_name="Imagen Banner Otras Vistas",help_text="Imagen del Banner en el resto de las vistas")
    address = models.CharField(max_length=255, verbose_name="Direccion", blank=True, null=True)
    horario = models.CharField(max_length=255, verbose_name="Horarios",help_text="Horarios", blank=True, null=True)
    email = models.EmailField(verbose_name="Correo de Contactos", blank=True, null=True,help_text="Correo que aparece en la página contactos")
    map_addres = models.TextField(verbose_name="Direccion google maps, src", help_text="Mapa de la ubicación del negocio")
    phone = models.CharField(max_length=255, verbose_name="Telefono")
    face = models.URLField(verbose_name="Facebook",  blank=True, null=True)
    inst = models.URLField(verbose_name="Instagram", blank=True, null=True)
    twit = models.URLField(verbose_name="Twitter",  blank=True, null=True)
    yout = models.URLField(verbose_name="YouTube", blank=True, null=True)
    link = models.URLField(verbose_name="Linkedin", blank=True, null=True)

    class Meta:
        verbose_name_plural = "A. General"

    def __str__(self):
        return str(self.name)

class Blog(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="creado")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Modificado")
    title = models.CharField(max_length=255, verbose_name="Título")
    text_small = models.CharField(max_length=255, verbose_name="Texto pequeño", blank=True, null=True)
    descripcion = RichTextField(verbose_name="Descripción")
    active = models.BooleanField(verbose_name="Destacado", default=False)
    image = models.ImageField(upload_to="blog/%Y/%m/%d", verbose_name="Imagen Principal", null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog-detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name_plural = "B. Blog"


class Galery_blog(models.Model):
    created_at = models.DateField(verbose_name="Creado", auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Modificado")
    image = models.ImageField(upload_to="galery_blog", verbose_name="Imagen", null=True)
    blog = models.ForeignKey(Blog, models.CASCADE, verbose_name="Blog", null=True)

    def __str__(self):
        return self.blog.title

    class Meta:
        verbose_name_plural = "C. Galería del Blog"

class Info_extra(models.Model):
    created_at = models.DateField(verbose_name="Creado", auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Modificado")
    title = models.CharField(max_length=255, verbose_name="Título")
    cantidad = models.IntegerField(verbose_name="Cantidad", blank=True, null=True)
    image = models.ImageField(upload_to="info_extra", verbose_name="Logo", null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "D. Información Extra"

class Sponsor(models.Model):
    created_at = models.DateField(verbose_name="Creado", auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Modificado")
    name = models.CharField(max_length=255, verbose_name="Nombre")
    image = models.ImageField(upload_to="sponsor", verbose_name="Logo", null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "E. Patrocinadores"

class Moneda(models.Model):
    created_at = models.DateTimeField(verbose_name="Creado", auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Modificado")
    name = models.CharField(max_length=255, verbose_name="Tipo de Moneda")

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name_plural = "F. Tipos de Monedas"

class Planes(models.Model):
    created_at = models.DateField(verbose_name="Creado", auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Modificado")
    name = models.CharField(max_length=255, verbose_name="Nombre")
    moneda = models.ForeignKey(Moneda, models.CASCADE, verbose_name="Tipo de Moneda")
    price = models.FloatField(default=0, verbose_name="Precio del plan")
    descripcion = RichTextField(verbose_name="Descripción", default='')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "G. Planes de boda"


class Tipo_galery(models.Model):
    created_at = models.DateField(verbose_name="Creado", auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Modificado")
    name = models.CharField(max_length=255, verbose_name="Nombre")
    active = models.BooleanField(verbose_name="Visible en inicio", default=False)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "H. Tipo de Galería"

class Galery(models.Model):
    created_at = models.DateField(verbose_name="Creado", auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Modificado")
    title = models.CharField(max_length=255, verbose_name="Título")
    text = models.CharField(max_length=255, verbose_name="Texto")
    active = models.BooleanField(verbose_name="Visible en inicio", default=False)
    image = models.ImageField(upload_to="galery", verbose_name="Imagen", null=True)
    tipo = models.ForeignKey(Tipo_galery, models.CASCADE, verbose_name="Tipo de Galería")


    def __str__(self):
        return self.title
    class Meta:
        verbose_name_plural = "I. Galería"


class Service(models.Model):
    created_at = models.DateField(verbose_name="Creado", auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Modificado")
    name = models.CharField(max_length=255, verbose_name="Nombre del servicio")
    text = RichTextField(verbose_name="Texto")
    image = models.ImageField(upload_to="service", verbose_name="Imagen", null=True)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "K. Servicios"

class Solicitud(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="created_at")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="updated_at")
    email = models.EmailField(max_length=255,verbose_name="Email")
    phone = models.CharField(max_length=255, verbose_name="Teléfono", default='')
    full_name = models.CharField(max_length=255, verbose_name="Nombre Completo")
    servicio = models.ForeignKey(Service, models.CASCADE, verbose_name="Tipo de Servicio")
    text = models.TextField(verbose_name="Mensaje")
    def __str__(self):
        return self.servicio.name


    class Meta:
        verbose_name_plural = "J. Solicitudes"

class Team(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="created_at")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="updated_at")
    name = models.CharField(max_length=255, verbose_name="Nombre Completo")
    ocupation = models.CharField(max_length=255, verbose_name="Ocupación")
    image = models.ImageField(upload_to="team", verbose_name="Imagen", null=True)
    face = models.URLField(verbose_name="Facebook", blank=True, null=True)

DreamApp/forms.py
from django import forms
from django.forms import *
from DreamApp import models

class SolicitudForm(ModelForm):
    empty_label_message = 'Servicios'

    servicio = ModelChoiceField(
        queryset=models.Service.objects.all(), empty_label=empty_label_message)

    class Meta:
        model = models.Solicitud
        fields = ("servicio","email","full_name","phone","text")



        widgets = {
            'full_name': TextInput(attrs={'class': 'form-control', 'placeholder': 'Su Nombre'}),
            'phone': TextInput(attrs={'class': 'form-control', 'placeholder': 'Su telefono'}),
            'text': Textarea(attrs={'class': 'form-control', 'placeholder': 'Su mensaje'}),
            'email': EmailInput(attrs={'class': 'form-control', 'placeholder': 'Su correo'}),
            'servicio': widgets.Select(attrs={'class': 'form-control required','placeholder':'Servicio'}),
        }

DreamApp/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from DreamApp import models, forms
from Dream import settings
import sweetify
from django.template.loader import render_to_string
from datetime import datetime
from django.core.mail import send_mail
from django.utils.translation import ugettext_lazy as _


# Create your views here.
def home(request):
    if request.POST:
        form = forms.SolicitudForm(request.POST)
        if form.is_valid():
            full_name = form.cleaned_data['full_name']
            email = form.cleaned_data['email']
            phone = form.cleaned_data['phone']
            text = form.cleaned_data['text']
            servicio = form.cleaned_data['servicio']
            solicitud = models.Solicitud(full_name=full_name, email=email, phone=phone, text=text, servicio=servicio)
            solicitud.save()

            entidad = models.General.objects.get()
            subject = _('Nueva Solicitud')
            message = render_to_string('dream_app/correo.html', {
                'reserva': solicitud,
            })
            send_mail(subject,
                      message,
                      settings.EMAIL_HOST_USER,
                      [entidad.email]  # destinatario
                      )
            sweetify.success(request, 'Solicitud realizada con éxito', button='Ok', timer=5000)
            return HttpResponseRedirect('/')
    services = models.Service.objects.all()
    info = models.Info_extra.objects.all()
    sponsor = models.Sponsor.objects.all()
    blog = models.Blog.objects.order_by("-id").all()[:3]
    tipo = models.Tipo_galery.objects.filter(active=True).all()
    fotos = models.Galery.objects.filter(active=True).all()[:6]
    return render(request, 'dream_app/inicio.html',
                  {'services': services, 'info': info, 'blog': blog, 'sponsor': sponsor, 'fotos': fotos, 'tipo': tipo})


def services(request):
    if request.POST:
        form = forms.SolicitudForm(request.POST)
        if form.is_valid():
            full_name = form.cleaned_data['full_name']
            email = form.cleaned_data['email']
            phone = form.cleaned_data['phone']
            text = form.cleaned_data['text']
            servicio = form.cleaned_data['servicio']
            solicitud = models.Solicitud(full_name=full_name, email=email, phone=phone, text=text, servicio=servicio)
            solicitud.save()

            entidad = models.General.objects.get()
            subject = _('Nueva Solicitud')
            message = render_to_string('dream_app/correo.html', {
                'reserva': solicitud,
            })
            send_mail(subject,
                      message,
                      settings.EMAIL_HOST_USER,
                      [entidad.email]  # destinatario
                      )
            sweetify.success(request, 'Solicitud realizada con éxito', button='Ok', timer=5000)
            return HttpResponseRedirect('/services/')
    services = models.Service.objects.all()
    planes = models.Planes.objects.all()
    return render(request, 'dream_app/services.html', {'services': services, 'planes': planes})


def blogs(request, index):
    blog = models.Blog.objects.order_by("-id").all()
    paginator = Paginator(blog, 3, index)  # Show 25 contacts per page.
    page_number = request.GET.get('page')
    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        page_obj = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        page_obj = paginator.page(paginator.num_pages)
    # page_obj = paginator.get_page(page_number)
    destacado = models.Blog.objects.filter(active=True).all()
    return render(request, 'dream_app/blog.html', {'page_obj': page_obj, 'destacado': destacado })


def blog_detail(request, pk):
    blog = get_object_or_404(models.Blog, pk=pk)
    try:
        the_next = blog.get_next_by_created_at()
    except:
        the_next = None
    try:
        the_prev = blog.get_previous_by_created_at()
    except:
        the_prev = None
    blogs = models.Blog.objects.exclude(pk=pk).order_by("-id").all()[:3]
    destacado = models.Blog.objects.filter(active=True).all()
    return render(request, 'dream_app/blog_details.html',
                  {'blog': blog, 'destacado': destacado, 'blogs': blogs, 'the_next': the_next, 'the_prev': the_prev})


# Funcion para la vista Contactos
def contact(request):
    if request.POST:
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        comentario = models.Contact.objects.create(name=name, email=email, text=message)
        comentario.save()
        entidad = models.General.objects.get()
        subject = _('Nuevo Mensaje')
        message = render_to_string('dream_app/correo_contact.html', {
            'mensaje': comentario,
        })
        send_mail(subject,
                  message,
                  settings.EMAIL_HOST_USER,
                  [entidad.email]  # destinatario
                  )
        sweetify.success(request, 'Mensaje enviado con éxito', button='Ok', timer=5000)
        return HttpResponseRedirect("/contact/")
    return render(request, "dream_app/contact.html")

def team(request):
    team = models.Team.objects.all()
    return render(request, 'dream_app/team.html', {'team': team})


def about(request):
    info = models.Info_extra.objects.all()
    opiniones = models.Opinion.objects.all()
    team = models.Team.objects.all()
    return render(request, 'dream_app/about.html', {'info': info, 'opiniones': opiniones, 'team': team})


def galery(request):
    tipo = models.Tipo_galery.objects.all()
    fotos = models.Galery.objects.all()
    return render(request, 'dream_app/portfolio.html', {'fotos': fotos, 'tipo': tipo})

DreamApp/templates/dream_app/blog.html
{% extends 'dream_app/index.html' %}
{% load static %}
{% load thumbnail %}
{% block blog_active %}
    <li class="active"><a href="{% url 'blog' 1%}">Blog</a></li>
{% endblock %}
    <!-- Header End -->
{% block content %}
    <!-- Breadcrumb Begin -->
    <div class="breadcrumb-option set_bg" style="background-image: url({{ general.image_banner_2.url }});
            background-repeat: no-repeat;
            background-size: cover;
            background-position: top center;
            height: 600px">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__text">
                        <h2>Blog</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Blog Section Begin -->
    <section class="blog spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-8">
                    {% for blo in page_obj %}
                    <div class="blog__item">
                        <div class="blog__item__title">
                            <ul>
                                <li>{{ blo.text_small }}</li>
                                <li>{{ blo.created_at }}</li>
                            </ul>
                            <h2>{{ blo.title }}</h2>
                        </div>
                        <div class="blog__item__pic__slider owl-carousel">
                            <img height="440px" src="{% thumbnail blo.image 750x0 crop %}">
                            {% for img in blo.galery_blog_set.all %}
                            <img height="440px" src="{% thumbnail img.image 750x0 crop %}">
                            {% endfor %}
                        </div>
                        <div class="blog__item__text">
                            <p>{{ blo.descripcion|safe|striptags|truncatechars:200 }} </p>
                            <a href="{% url 'blog-detail' blo.pk %}">LEER MÁS</a>
                        </div>
                    </div>
                    {% endfor %}
                        <div class="pagination__option">

                            {% if page_obj.has_previous %}
                                <a href="?page={{ page_obj.previous_page_number }}"><span class="arrow_left"></span></a>
                            {% else %}
                                <span> No más </span>
                            {% endif %}
                            {% for page_number in page_obj.paginator.page_range %}

                                {% ifequal page_number  page_obj.number %}
                                    <a class="active" href="#">{{ page_number }}</a>

                                {% else %}
                                    <a href="?page={{ page_number }}">{{ page_number }}</a>

                                {% endifequal %}
                            {% endfor %}

                            {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}"><span class="arrow_right"></span></a>
                            {% else %}
                                <span> No más </span>
                            {% endif %}

                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4">
                        <div class="blog__sidebar">
                            <div class="blog__sidebar__item">
                                <h4>Blogs Destacados</h4>
                            {% if destacado %}
                                 {% for dest in destacado %}
                                <a href="{% url 'blog-detail' dest.id %}" class="blog__sidebar__recent__item">
                                    <div class="blog__sidebar__recent__item__pic">
                                        <img width="80px" height="80px" src="{% thumbnail dest.image 750x0 crop %}" alt="">
                                    </div>
                                    <div class="blog__sidebar__recent__item__text">
                                        <h5>{{ dest.title|safe|striptags|truncatechars:45 }}</h5>
                                        <span>{{ dest.created_at }}</span>
                                    </div>
                                </a>
                                 {% endfor %}
                            {% else %}
                            <h5>No hay blogs destacados</h5>
                            {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Blog Section End -->
{% endblock %}

DreamApp/templates/dream_app/blog_details.html
{% extends 'dream_app/index.html' %}
{% load static %}
{% load thumbnail %}
{% block blog_active %}
    <li class="active"><a href="{% url 'blog' 1%}">Blog</a></li>
{% endblock %}
{% block content %}
    <!-- Breadcrumb Begin -->
    <div class="breadcrumb-option set_bg" style="background-image: url({{ general.image_banner_2.url }});
            background-repeat: no-repeat;
            background-size: cover;
            background-position: top center;
            height: 600px">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__text">
                        <h2>Blog Detalle</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Blog Details Section Begin -->
    <section class="blog-details spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-8">
                    <div class="blog__details__content">
                        <div class="blog__item">
                            <div class="blog__item__title">
                                <ul>
                                    <li>{{ blog.text_small }}</li>
                                    <li>{{ blog.created_at }}</li>
                                </ul>
                                <h2>{{ blog.title }}</h2>
                            </div>
                            <div class="blog__item__pic set_bg">
                                 <img height="440px" width="750px" src="{% thumbnail blog.image 750x0 crop %}">
                            </div>
                            <div class="blog__item__text">
                                <p>{{ blog.descripcion|safe }} </p>
                            </div>
                        </div>


            <div class="blog__details__pic">
                <div class="tz-gallery">
                    {% for img in blog.galery_blog_set.all %}
                <a class="image" href="{% thumbnail img.image 750x0 crop %}">
                    <img src="{% thumbnail img.image 750x0 crop %}" alt="..." width="250px" height="200px">
                </a>
                    {% endfor %}
                </div>
            </div>

                        <div class="blog__details__widget">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="blog__details__social">
                                        <span><i class="fa fa-share"></i> Compartir</span>
                                           <a target="_blank" href="https://twitter.com/intent/tweet?text={{ blog.title }}&url={{ request.build_absolute_uri }}"><i class="fa fa-twitter"></i></a>
                                           <a target="_blank" href="https://www.facebook.com/share.php?u={{ request.build_absolute_uri }}&title={{ blog.title }}"><i class="fa fa-facebook"></i></a>
                                           <a target="_blank" href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title={{ blog.title }}"><i class="fa fa-linkedin"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="blog__details__btns">
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                            {% if the_prev %}
                                    <a href="{{ the_prev.get_absolute_url }}" class="blog__details__btns__item">
                                        <i class="fa fa-angle-left"></i>
                                        Anterior
                                    </a>
                                    {% else %}
                                    No más
                                    {% endif %}

                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                        {% if the_next %}
                                    <a href="{{ the_next.get_absolute_url }}" class="blog__details__btns__item blog__details__btns__item--next">
                                        Siguiente
                                        <i class="fa fa-angle-right"></i>
                                    </a>
                                     {% else %}
                                    No más
                                    {% endif %}

                                </div>
                            </div>
                        </div>
                        <div class="blog__details__recent">
                            <h4>Blogs Recientes</h4>
                            <div class="row">
                                {% for blog in blogs %}
                                <div class="col-lg-4 col-md-6 col-sm-6">
                                    <div class="blog__details__recent__item">
                                        <img width="230px" height="153px" src="{% thumbnail blog.image 750x0 crop %}" alt="">
                                        <h5><a href="{% url 'blog-detail' blog.id %}">{{ blog.title }} </a></h5>
                                        <span>{{ blog.created_at }}</span>
                                    </div>
                                </div>
                                {% endfor %}

                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4">
                    <div class="blog__sidebar">
                        <div class="blog__sidebar__item">
                            <h4>Blogs Destacados</h4>
                                   {% if destacado %}
                                 {% for dest in destacado %}
                                <a href="{% url 'blog-detail' dest.id %}" class="blog__sidebar__recent__item">
                                    <div class="blog__sidebar__recent__item__pic">
                                        <img width="80px" height="80px" src="{% thumbnail dest.image 750x0 crop %}" alt="">
                                    </div>
                                    <div class="blog__sidebar__recent__item__text">
                                        <h5>{{ dest.title|safe|truncatechars:45 }}</h5>
                                        <span>{{ dest.created_at }}</span>
                                    </div>
                                </a>
                                 {% endfor %}
                            {% else %}
                            <h5>No hay blogs destacados</h5>
                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Blog Details Section End -->
{% endblock %}

DreamApp/templates/dream_app/correo.html
{% load i18n %}
{% autoescape off %}
Hola: Se ha realizado una solicitud a nombre de: {{ reserva.full_name }}

con Teléfono: {{ reserva.phone }} y Correo: {{ reserva.email }}

Servicio solicitado: {{ reserva.servicio }}

Mensaje: {{ reserva.text }}

Gracias por usar nuestro sitio!

{% endautoescape %}

DreamApp/templates/dream_app/correo_contact.html
{% load i18n %}
{% autoescape off %}
Hola: Ha recibido un mensaje de: {{ mensaje.name }}

con Correo: {{ mensaje.email }}

Mensaje: {{ mensaje.text }}

Gracias por usar nuestro sitio!

{% endautoescape %}

DreamApp/templates/dream_app/inicio.html
{% extends 'dream_app/index.html' %}
{% block inicio_active %}
         <li class="active"><a href="{% url 'home' %}">Inicio</a></li>
{% endblock %}

DreamApp/templates/dream_app/main.html
<a href="https://colorlib.com/wp/templates/"><img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>
<br>
<p style="text-align:center; color:red;"><strong>Copyright information for the template can't be altered/removed unless you purchase a license.</strong>

<p style="text-align:center;"><strong>Removing copyright information without the license will result in suspension of your hosting and/or domain name(s).</strong>

<p style="text-align:center;"><strong>More information about the license is available <a href="https://colorlib.com/wp/licence/">here</a></strong>.</p>

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>